networks:
  influxdb:
  npm_net:
    external: true

services:
  influxdb:
    image: influxdb:2.7 # Use explicit version
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    networks:
      - influxdb
    environment:
     - INFLUXDB_DATA_ENGINE=tsm1
     - INFLUXDB_REPORTING_DISABLED=false
     - INFLUXDB_GRAPHITE_0_ENABLED=true
     - INFLUXDB_GRAPHITE_0_DATABASE=graphite
     - INFLUXDB_GRAPHITE_0_BIND_ADDRESS=:2003
     - INFLUXDB_GRAPHITE_PROTOCOL=tcp
     - INFLUXDB_GRAPHITE_BATCH_SIZE=1000
    volumes:
      - /docker/grafana/influxdb/data:/var/lib/influxdb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "influx", "ping", "-host", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   networks:
  #     - influxdb
  #   volumes:
  #     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:10.4.2 # Use explicit version
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - influxdb
      - npm_net
    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    user: "0"
    depends_on:
      - influxdb
    volumes:
      - /docker/grafana/grafana/data:/var/lib/grafana
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 30s
      timeout: 10s
      retries: 5
