networks:
  influxdb:
  npm_net:
   external: true

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    networks:
      - influxdb
    environment:
     - INFLUXDB_DATA_ENGINE=tsm1
     - INFLUXDB_REPORTING_DISABLED=false
     - INFLUXDB_GRAPHITE_0_ENABLED=true
     - INFLUXDB_GRAPHITE_0_DATABASE=graphite
     - INFLUXDB_GRAPHITE_0_BIND_ADDRESS=:2003
     - INFLUXDB_GRAPHITE_PROTOCOL=tcp
     - INFLUXDB_GRAPHITE_BATCH_SIZE=1000
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /docker/grafana/influxdb/data:/var/lib/influxdb

  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   networks:
  #     - influxdb
  #   volumes:
  #     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - influxdb
    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /docker/grafana/grafana/data:/var/lib/grafana
